# Generated by Django 3.2.7 on 2021-09-12 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commet',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commets', to='blog.post'),
        ),
        migrations.AlterField(
            model_name='commet',
            name='title',
            field=models.TextField(blank=True, max_length=127, null=True),
        ),
    ]
