# Generated by Django 3.2.7 on 2021-09-12 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210912_1228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commet',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='name',
        ),
    ]
